// fe-sinhvien/src/App.jsx
import React from 'react';
import { useStudentSystem } from './hooks/useStudentSystem';
import StudentApp from './pages/StudentApp';

export default function App() {
  const sysAPI = useStudentSystem();

  return (
    <StudentApp
      db={sysAPI.db}
      user={sysAPI.auth.student.user}
      sysAPI={sysAPI}
    />
  );
}

// fe-sinhvien/src/App.vue
<script setup>
import { onMounted, onUnmounted } from 'vue';
import { storeToRefs } from 'pinia';
import { useStudentStore } from './stores/studentStore';
import StudentApp from './pages/StudentApp.vue';

const sysAPI = useStudentStore();
const { db, auth } = storeToRefs(sysAPI);

onMounted(() => {
  sysAPI.setupSignalR();
});

onUnmounted(() => {
  sysAPI.cleanupSignalR();
});
</script>

<template>
  <StudentApp
    :db="db"
    :user="auth.student.user"
    :sysAPI="sysAPI"
  />
</template>
